name: Docs to PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  push-pdf:
    name: push PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: README.md
          output_dir: pdf
          build_html: false
          theme: pdf/theme.css
      - name: push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "docs: PDFの更新 【$(date '+%Y/%m/%d')】"
          git push origin main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
