name: Generate PDF
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  node-version: "20.x"
  pnpm-version: "8"

jobs:
  generate-pdf:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: "pnpm"
      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles(format('{0}{1}', github.workspace, '/pnpm-lock.yaml')) }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NOTE: 日本語フォントがLinuxにインストールされていないのでインストールする
      - name: Install fonts-noto
        run: sudo apt install fonts-noto
      - name: Generate PDF
        run: pnpm gen:pdf
      - name: push
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "docs: PDFの更新 【$(date '+%Y/%m/%d')】"
          git push origin main
